
package org.rsna.isn.retrievecontent.rad69;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.1-hudson-28-
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ImagingDocumentSource_PortType", targetNamespace = "urn:ihe:rad:xdsi-b:2009")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ImagingDocumentSourcePortType {


    /**
     * 
     * @param body
     * @return
     *     returns org.rsna.getimaging.rad69.RetrieveDocumentSetResponseType
     */
    @WebMethod(operationName = "ImagingDocumentSource_RetrieveImagingDocumentSet", action = "urn:ihe:rad:2009:RetrieveImagingDocumentSet")
    @WebResult(name = "RetrieveDocumentSetResponse", targetNamespace = "urn:ihe:iti:xds-b:2007", partName = "body")
    public RetrieveDocumentSetResponseType imagingDocumentSourceRetrieveImagingDocumentSet(
        @WebParam(name = "RetrieveImagingDocumentSetRequest", targetNamespace = "urn:ihe:rad:xdsi-b:2009", partName = "body")
        RetrieveImagingDocumentSetRequestType body);

}
