//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.15 at 06:50:35 PM CST 
//


package org.rsna.isn.retrievecontent.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}documentuniqueid"/>
 *         &lt;element ref="{}rsnaid"/>
 *         &lt;element ref="{}studyinstanceuid"/>
 *         &lt;element ref="{}studydescription"/>
 *         &lt;element ref="{}modality"/>
 *         &lt;element ref="{}accessionnumber"/>
 *         &lt;element ref="{}studydate"/>
 *         &lt;element ref="{}studytime"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "documentuniqueid",
    "rsnaid",
    "studyinstanceuid",
    "studydescription",
    "modality",
    "accessionnumber",
    "studydate",
    "studytime"
})
@XmlRootElement(name = "documentinfotype")
public class Documentinfotype {

    @XmlElement(required = true)
    protected String documentuniqueid;
    @XmlElement(required = true)
    protected String rsnaid;
    @XmlElement(required = true)
    protected String studyinstanceuid;
    @XmlElement(required = true)
    protected String studydescription;
    @XmlElement(required = true)
    protected String modality;
    @XmlElement(required = true)
    protected String accessionnumber;
    @XmlElement(required = true)
    protected String studydate;
    @XmlElement(required = true)
    protected String studytime;

    /**
     * Gets the value of the documentuniqueid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentuniqueid() {
        return documentuniqueid;
    }

    /**
     * Sets the value of the documentuniqueid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentuniqueid(String value) {
        this.documentuniqueid = value;
    }

    /**
     * Gets the value of the rsnaid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRsnaid() {
        return rsnaid;
    }

    /**
     * Sets the value of the rsnaid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRsnaid(String value) {
        this.rsnaid = value;
    }

    /**
     * Gets the value of the studyinstanceuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStudyinstanceuid() {
        return studyinstanceuid;
    }

    /**
     * Sets the value of the studyinstanceuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStudyinstanceuid(String value) {
        this.studyinstanceuid = value;
    }

    /**
     * Gets the value of the studydescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStudydescription() {
        return studydescription;
    }

    /**
     * Sets the value of the studydescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStudydescription(String value) {
        this.studydescription = value;
    }

    /**
     * Gets the value of the modality property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModality() {
        return modality;
    }

    /**
     * Sets the value of the modality property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModality(String value) {
        this.modality = value;
    }

    /**
     * Gets the value of the accessionnumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccessionnumber() {
        return accessionnumber;
    }

    /**
     * Sets the value of the accessionnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccessionnumber(String value) {
        this.accessionnumber = value;
    }

    /**
     * Gets the value of the studydate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStudydate() {
        return studydate;
    }

    /**
     * Sets the value of the studydate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStudydate(String value) {
        this.studydate = value;
    }

    /**
     * Gets the value of the studytime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStudytime() {
        return studytime;
    }

    /**
     * Sets the value of the studytime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStudytime(String value) {
        this.studytime = value;
    }

}
