//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.15 at 06:50:35 PM CST 
//


package org.rsna.retrievedocumentset.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}documentUniqueID"/>
 *         &lt;element ref="{}rsnaID"/>
 *         &lt;element ref="{}transferSyntaxUID"/>
 *         &lt;element ref="{}studyInstanceUID"/>
 *         &lt;element ref="{}series"/>
 *         &lt;element ref="{}studyDescription"/>
 *         &lt;element ref="{}modality"/>
 *         &lt;element ref="{}accessionNumber"/>
 *         &lt;element ref="{}studyDate"/>
 *         &lt;element ref="{}studyTime"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "documentUniqueID",
    "rsnaID",
    "transferSyntaxUID",
    "studyInstanceUID",
    "series",
    "studyDescription",
    "modality",
    "accessionNumber",
    "studyDate",
    "studyTime"
})
@XmlRootElement(name = "document")
public class Document {

    @XmlElement(required = true)
    protected String documentUniqueID;
    @XmlElement(required = true)
    protected String rsnaID;
    @XmlElement(required = true)
    protected String transferSyntaxUID;
    @XmlElement(required = true)
    protected String studyInstanceUID;
    @XmlElement(required = true)
    protected Series series;
    @XmlElement(required = true)
    protected String studyDescription;
    @XmlElement(required = true)
    protected String modality;
    @XmlElement(required = true)
    protected String accessionNumber;
    @XmlElement(required = true)
    protected String studyDate;
    @XmlElement(required = true)
    protected String studyTime;

    /**
     * Gets the value of the documentUniqueID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentUniqueID() {
        return documentUniqueID;
    }

    /**
     * Sets the value of the documentUniqueID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentUniqueID(String value) {
        this.documentUniqueID = value;
    }

    /**
     * Gets the value of the rsnaID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRsnaID() {
        return rsnaID;
    }

    /**
     * Sets the value of the rsnaID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRsnaID(String value) {
        this.rsnaID = value;
    }

    /**
     * Gets the value of the transferSyntaxUID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransferSyntaxUID() {
        return transferSyntaxUID;
    }

    /**
     * Sets the value of the transferSyntaxUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransferSyntaxUID(String value) {
        this.transferSyntaxUID = value;
    }

    /**
     * Gets the value of the studyInstanceUID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStudyInstanceUID() {
        return studyInstanceUID;
    }

    /**
     * Sets the value of the studyInstanceUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStudyInstanceUID(String value) {
        this.studyInstanceUID = value;
    }

    /**
     * Gets the value of the series property.
     * 
     * @return
     *     possible object is
     *     {@link Series }
     *     
     */
    public Series getSeries() {
        return series;
    }

    /**
     * Sets the value of the series property.
     * 
     * @param value
     *     allowed object is
     *     {@link Series }
     *     
     */
    public void setSeries(Series value) {
        this.series = value;
    }

    /**
     * Gets the value of the studyDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStudyDescription() {
        return studyDescription;
    }

    /**
     * Sets the value of the studyDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStudyDescription(String value) {
        this.studyDescription = value;
    }

    /**
     * Gets the value of the modality property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModality() {
        return modality;
    }

    /**
     * Sets the value of the modality property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModality(String value) {
        this.modality = value;
    }

    /**
     * Gets the value of the accessionNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccessionNumber() {
        return accessionNumber;
    }

    /**
     * Sets the value of the accessionNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccessionNumber(String value) {
        this.accessionNumber = value;
    }

    /**
     * Gets the value of the studyDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStudyDate() {
        return studyDate;
    }

    /**
     * Sets the value of the studyDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStudyDate(String value) {
        this.studyDate = value;
    }

    /**
     * Gets the value of the studyTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStudyTime() {
        return studyTime;
    }

    /**
     * Sets the value of the studyTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStudyTime(String value) {
        this.studyTime = value;
    }

}
